# default config.yml

AutoUpdate: true

# Anti-Spam

LimitLogins: 5 #Players will be kicked if they join twice within a space of this amount of seconds
CapsPercentage: 70 #If a players chat contains more then this percentage of capitals it will be changed to lower case
MaxWordLength: 15 #If a player types a word longer then this (for example 'asdgasdgasgaga') it will be blocked
CensorLimit: 70 #If more then this percentage of a message is censored it is blocked
ChatSpam: 1 #Limit between the time a player can chat again

BannedWords: #Any words in this list will be blocked
   #- Fuck
   #- Bitch
   #- Bastard
   #- Whore

# Protection

MinimumZoneSize: 6

ProtectChests: true #If a player places a chest and has no protections, a new one is created around the chest

# Land

BuyableLand: true
StartLand: 100 # Width X Length ( 10 x 10 ) (Must be a square number)

LandGain: 20 #The amount you gain
LandDelay: 1200 #The delay between each gain of land
SendMessage: true #Sends a message when they gain land

# Items

#Any items you don't want people to be able to use in other peoples protections outside of normal
#mining / placing (For example, a rod of protection from this plugin)
BlockedItems:
   - 2256
   - 2257
   - 2258
   - 2259
   - 2260
   - 2261
   - 2262
   - 2263
   - 2264
   - 2265
   - 2266
   - 2267
   - 351
   - 381
   - 385

# Block

RightClickIronDoor: true

FireBurn: false
FireSpread: false

# Players

PlayersTrampleCrops: true

PlayersCanCreatePortals: true

PreventPVPLog: true
PreventPVPTeleport: true

# Entity

EntitiesTrampleCrops: false

TNTDamageEntity: true
TNTBlockDamage: false

TNTCartDamageEntity: true
TNTCartBlockDamage: false

CreeperDamageEntity: true
CreeperBlockDamage: false

GhastDamageEntity: true
GhastBlockDamage: true

WitherDamageEntity: true
WitherBlockDamage: false

WitherHeadDamageEntity: true
WitherHeadBlockDamage: false

EnderCrystalDamageEntity: true
EnderCrystalBlockDamage: false

EndermenBlockChange: false

EnderDragonBlockDamage: false
ZombiesBreakDoors: true